In [23]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

In [24]:
# add csv file 
data = pd.read_csv('Churn_Modelling.csv')

data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [25]:
# remove or drop unnecessary columns

data = data.drop(['RowNumber', 'CustomerId', 'Surname', 'Gender', 'Exited'], axis=1)

data.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,42,2,0.00,1,1,1,101348.88
1,608,Spain,41,1,83807.86,1,0,1,112542.58
2,502,France,42,8,159660.80,3,1,0,113931.57
3,699,France,39,1,0.00,2,0,0,93826.63
4,850,Spain,43,2,125510.82,1,1,1,79084.10


In [26]:
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
onehot_encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [28]:
geo_encoder_df = pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

,Geography_France,Geography_Germany,Geography_Spain
0,1.0,0.0,0.0
1,0.0,0.0,1.0
2,1.0,0.0,0.0
3,1.0,0.0,0.0
4,0.0,0.0,1.0
...,...,...,...
9995,1.0,0.0,0.0
9996,1.0,0.0,0.0
9997,1.0,0.0,0.0
9998,0.0,1.0,0.0


In [29]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis=1)
data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0


In [30]:
with open ('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [31]:
data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0


In [32]:
# Divide data into the dependent and independent features

X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

# split the data into thetraining  and testing sets

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# scale these features

# Scale input features
scaler_x = StandardScaler()
X_train_scaled = scaler_x.fit_transform(X_train)
X_test_scaled = scaler_x.transform(X_test)

# Scale target (y)
scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1)) 


# # 7. Linear Regression Model
# model = LinearRegression()
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)


In [33]:
X_train_scaled

array([[ 0.35649971, -0.6557859 ,  0.34567966, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.29493847, -0.3483691 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.3900109 ,  1.03972843, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  1.15059039, -1.38944225, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [34]:
X_test_scaled

array([[-0.57749609, -0.6557859 , -0.69539349, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.3900109 , -1.38944225, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743,  0.48508334, -0.3483691 , ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987,  0.77030065,  0.69270405, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609, -0.94100321, -0.3483691 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.00972116, -1.38944225, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [35]:
y_test_scaled

array([[-1.01960511],
       [ 0.79888291],
       [-0.72797953],
       ...,
       [-1.16591585],
       [-0.41163463],
       [ 0.12593183]])

In [36]:
#  save the scaler file 

with open ('scaler_X.pkl', 'wb') as file:
    pickle.dump(scaler_x, file)


with open ('scaler_y.pkl', 'wb') as file:
    pickle.dump(scaler_y, file)

In [37]:
import tensorflow as tf  
from tensorflow.keras.models import Sequential  # type: ignore
from tensorflow.keras.layers import Dense     # type: ignore
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard # type: ignore
from sklearn.metrics import mean_absolute_error, r2_score 

import datetime

In [38]:
(X_test.shape[1],)

(10,)

In [39]:
# build our salary prediction ANN model 
model = Sequential([
    Dense(512,activation='relu', input_shape=(X_train.shape[1],)),
    Dense(256,activation='relu'),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')
])

In [40]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 512)               5632      
                                                                 
 dense_6 (Dense)             (None, 256)               131328    
                                                                 
 dense_7 (Dense)             (None, 128)               32896     
                                                                 
 dense_8 (Dense)             (None, 64)                8256      
                                                                 
 dense_9 (Dense)             (None, 32)                2080      
                                                                 
 dense_10 (Dense)            (None, 1)                 33        
                                                                 
Total params: 180225 (704.00 KB)
Trainable params: 180

In [41]:
# Optimizing model
import tensorflow

opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [42]:
# compile the model

model.compile(optimizer='adam',loss='mean_absolute_error',)

In [43]:
# train the model {early stopping method}

early_stop = EarlyStopping(monitor='val_loss', patience=100)

history = model.fit (
    X_train_scaled,y_train_scaled,validation_data=(X_test_scaled,y_test_scaled),epochs=100,batch_size = 32, callbacks=[early_stop]
)

Epoch 1/100
250/250 [==============================] - 7s 10ms/step - loss: 0.8672 - val_loss: 0.8665
Epoch 2/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8644 - val_loss: 0.8661
Epoch 3/100
250/250 [==============================] - 3s 10ms/step - loss: 0.8644 - val_loss: 0.8685
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8635 - val_loss: 0.8667
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8630 - val_loss: 0.8697
Epoch 6/100
250/250 [==============================] - 2s 8ms/step - loss: 0.8630 - val_loss: 0.8708
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.8638 - val_loss: 0.8673
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.8626 - val_loss: 0.8689
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.8623 - val_loss: 0.8679
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.8610 - val_

In [44]:
model.save('model.h5')

c:\Users\dell\OneDrive\Desktop\Advance projects\salary prediction ANN model\salary\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
